name: pipeline-workflow
on:
  push:
    branches:
      - 'main'
      - 'github_actions' #for debugging/dev purposes in this branch

jobs:   
  build-and-test-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # checkout repo
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # setup maven
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Change directory
        run: cd springbootWithPostgresql  # Change path to where pom.xml is located
        
      # build with automated run, run checks on code, update dependencies on the fly
      - name: Build with Maven
        working-directory: springbootWithPostgresql
        run: mvn --batch-mode --update-snapshots verify

      # Run tests
      - name: Run Java Tests
        working-directory: springbootWithPostgresql
        run: mvn test

      # create artifacts after job run
      - name: Create artifacts
        uses: actions/download-artifact@v3
        with:
          name: Application Build
          path: .github/workflows # specify an existing dir
          

