name: pipeline-workflow
on:
  push:
    branches:
      - 'main'

jobs:   
  build-and-test-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Change directory
        run: cd springbootWithPostgresql  # Change this to the path where your pom.xml is located
        
      - name: Build with Maven
        working-directory: springbootWithPostgresql
        run: mvn --batch-mode --update-snapshots verify

      # Run tests
      - name: Run Java Tests
        working-directory: springbootWithPostgresql
        run: mvn test
